env:
  GCP_PROJECT_ID: "buildkite-gcp-stack"
  GCP_BUILD_ZONE: "us-central1-a"

steps:
  - label: ":hammer: Build {{matrix.arch}} Image"
    command: .buildkite/scripts/build-and-publish-image {{matrix.arch}}
    plugins:
      - gcp-workload-identity-federation#v1.5.0:
          audience: "//iam.googleapis.com/projects/203137002969/locations/global/workloadIdentityPools/buildkite-image-builder-pool/providers/buildkite-image-builder"
          service-account: "gcp-image-builder-ci@buildkite-gcp-stack.iam.gserviceaccount.com"
      - docker#5.13.0:
          image: "hashicorp/packer:1.14"
    agents:
      queue: "gcp"
    artifact_paths:
      - "packer/linux/*.log"
      - ".buildkite/{{matrix.arch}}-image-name.txt"
    matrix:
      setup:
        arch:
          - amd64
          - arm64
