env:
  GCP_PROJECT_ID: "buildkite-gcp-stack"
  GCP_BUILD_ZONE: "us-central1-a"

steps:
  - label: ":hammer: Build {{matrix.arch}} Image"
    plugins:
      - gcp-workload-identity-federation#v1.5.0:
          audience: "//iam.googleapis.com/projects/203137002969/locations/global/workloadIdentityPools/buildkite-image-builder-pool/providers/buildkite-image-builder"
          service-account: "gcp-image-builder-ci@buildkite-gcp-stack.iam.gserviceaccount.com"
      - docker-compose#v5.12.1:
          run: packer-builder
          config: .buildkite/docker-compose.yml
          command: [".buildkite/scripts/build-and-publish-image", "{{matrix.arch}}"]
          propagate-gcp-auth-tokens: true
          run-as-user: true
    agents:
      queue: "gcp"
    artifact_paths:
      - "packer/linux/*.log"
      - ".buildkite/{{matrix.arch}}-image-name.txt"
    matrix:
      setup:
        arch:
          - x86-64
